const experienceData = [
  {
    id: 1,
    title: 'Frontend Developer-XLAB doo | June 2022 - 30th Nov 2023 ',
    techs: [
      'Html',
      'Markdown',
      'Scss',
      'Css',
      'JQuery',
      'Java Script',
      'TypeScript',
      'Bootstrap',
      'Vs Code',
      'Cypress',
      'Jira',
      'Gitlab,',
      'Google Developer Tools',
      'Vue JS,',
      'Angular,',
      'React Js',
      'Hugo Framework',
      'GO Templating',
      'Docker',
      'Adobe XD',
    ],
    responsibilities: [
      'Work in sprints in agile methodology, create and maintain front-end code for different projects applications (Vue, Angular, Hugo).',
      'Using bootstrap, scss and writing animations for making pixel perfect and responsive web apps and websites.',
      "Learned new Framework (Hugo) and migrated company's website from WordPress (PHP templating) to Hugo Framework (Golang templating).",
      "Contributed frontend implementation for EU's research and innovation funding programme (html, scss, vanilla java script).",
      'Cooperating with UX/UI design team understanding the need and functionality that has to be implemented.',
      'Bug fixing and updating existing projects.',
      'Cooperating with other team members on common projects.',
    ],
  },
  {
    id: 2,
    title: 'Soft Smart Services | Aug 2015 - Dec 2021',
    techs: [
      'Html',
      'Scss',
      'Css',
      'JQuery',
      'Java Script',
      'Php',
      'Sql',
      'Figma',
      'Bootstrap',
      'Google Developer Tools',
      'Github',
      'Google Adwords',
      'Google Analytics',
    ],

    responsibilities: [
      'Designing the website layout',
      'Developing websites',
      'WordPress',
      'WordPress plugins',
      'Woo-commerce',
      'Magento',
      'Manage website hosting',
      'SEO',
    ],
  },
  {
    id: 3,
    title: 'In Technologies | Apr 2013 - 2014 | ',
    responsibilities: [
      'software troubleshooting.',
      'Customer support for USA/CA/Britain,',
    ],
  },
];

export default experienceData;
