const projectData = [
  {
    id: 1,
    ref: "webApp",
    img: "images/projectPics/to-do-tasks.jpg",
    title: " To-do-app",
    code: "https://github.com/Ranjeet2311/To-Do-App-Vanilla-JS",
    demo: "https://old-portfolio0.netlify.app/app-demo/todo.html",
  },
  {
    id: 2,
    ref: "webApp",
    img: "images/projectPics/Weather.jpg",
    title: "Weathe App",
    code: "https://github.com/Ranjeet2311/Weather-App",
    demo: "https://old-portfolio0.netlify.app/app-demo/weather.html",
  },

  {
    id: 3,
    ref: "webApp",
    img: "images/projectPics/qr-code-bg.jpg",
    title: " QR-Code Generator",
    code: "https://github.com/Ranjeet2311/Qr-Code-Generator",
    demo: "https://qr-code-25-11.netlify.app/",
  },
  {
    id: 4,
    ref: "webApp",
    img: "images/projectPics/Personality-match.jpg",
    title: "Personality Match",
    code: "https://github.com/Ranjeet2311/Personality-Match",
    demo: "https://personality-match.netlify.app/",
  },

  {
    id: 5,
    ref: "webApp",
    img: "images/projectPics/weight-converter.jpg",
    title: " Weight converter",
    code: "https://github.com/Ranjeet2311/Weight-Converter",
    demo: "https://old-portfolio0.netlify.app/app-demo/weight-converter.html",
  },

  {
    id: 6,
    ref: "webApp",
    img: "images/projectPics/music-player.jpg",
    title: "Music player",
    code: "https://github.com/Ranjeet2311/Music-player",
    demo: "https://old-portfolio0.netlify.app/app-demo/music-player.html",
  },

  {
    id: 7,
    ref: "webApp",
    img: "images/projectPics/counter.jpg",
    title: "Counter",
    code: "https://github.com/Ranjeet2311/Counter-",
    demo: "https://old-portfolio0.netlify.app/app-demo/counter.html",
  },

  {
    id: 8,
    ref: "webApp",
    img: "images/projectPics/Digital-Clock.jpg",
    title: " Digital clock",
    code: "https://github.com/Ranjeet2311/Digital-Clock",
    demo: "https://old-portfolio0.netlify.app/app-demo/digital-clock.html",
  },

  {
    id: 9,
    ref: "webApp",
    img: "images/projectPics/play-music.jpg",
    title: "Tap the music",
    code: "https://github.com/Ranjeet2311/Tap-the-Music",
    demo: "https://old-portfolio0.netlify.app/app-demo/play-music.html",
  },

  {
    id: 10,
    ref: "webApp",
    img: "images/projectPics/Menu-display.jpg",
    title: "Menu display -filter",
    code: "https://github.com/Ranjeet2311/Dynamic-Menu-Display",
    demo: "https://old-portfolio0.netlify.app/app-demo/menu-display.html",
  },

  {
    id: 11,
    ref: "webApp",
    img: "images/projectPics/modal.jpg",
    title: "Best pictures from Europe",
    code: "https://github.com/Ranjeet2311/Modal",
    demo: "https://old-portfolio0.netlify.app/app-demo/modal.html",
  },
  {
    id: 12,
    ref: "webApp",
    img: "images/projectPics/diceGame.png",
    title: "Dice Game",
    code: "https://github.com/Ranjeet2311/Dice-Game",
    demo: "https://dazzling-heisenberg-3851ef.netlify.app/",
  },

  {
    id: 13,
    ref: "template",
    img: "images/projectPics/e-commerce-demo.png",

    title: "E-commerce-demo",
    code: "https://github.com/Ranjeet2311/Projects",
    demo: "https://old-portfolio0.netlify.app/app-demo/e-commerce-demo.html",
  },
  {
    id: 14,
    ref: "template",
    img: "images/projectPics/form-validation-e.jpg",
    title: "Form validation",
    code: "https://github.com/Ranjeet2311/Parcel-bundler",
    demo: "https://render-007.netlify.app/",
  },
  {
    id: 15,
    ref: "template",
    img: "images/projectPics/yoga-demo.png",
    title: "Yoga-demo",
    code: "https://github.com/Ranjeet2311/Projects",
    demo: "https://old-portfolio0.netlify.app/app-demo/yoga-demo.html",
  },
  {
    id: 16,
    ref: "template",
    img: "images/projectPics/tech-demo.jpg",
    title: "Tech-demo",
    code: "https://github.com/Ranjeet2311/Projects",
    demo: "https://old-portfolio0.netlify.app/app-demo/tech-demo.html",
  },
  {
    id: 17,
    ref: "template",
    img: "images/projectPics/car-service-demo.png",
    title: "Car service demo",
    code: "https://github.com/Ranjeet2311/Projects",
    demo: "https://old-portfolio0.netlify.app/app-demo/car-service.html",
  },
  {
    id: 18,
    ref: "template",
    img: "images/projectPics/game-sign-up.png",
    title: "Game-sign-up",
    code: "https://github.com/Ranjeet2311/Projects",
    demo: "https://old-portfolio0.netlify.app/app-demo/hero-page.html",
  },
  {
    id: 19,
    ref: "template",
    img: "images/projectPics/my-portfolio.png",
    title: "Old portfolio",
    code: "https://github.com/Ranjeet2311/Ranjeet2311.github.io",
    demo: "https://old-portfolio0.netlify.app/",
  },
  {
    id: 20,
    ref: "template",
    img: "images/projectPics/Animated-Boat.jpg",
    title: "Animated Boat",
    code: "https://github.com/Ranjeet2311/Boat-Animation",
    demo: "https://old-portfolio0.netlify.app/app-demo/animatedBoat.html",
  },
  {
    id: 21,
    ref: "template",
    img: "images/projectPics/Av-st-Template-demo.PNG",
    title: "Av-st-Template",
    code: "https://github.com/Ranjeet2311/frontend-_AV",
    demo: "https://av-st-template.netlify.app/",
  },

  {
    id: 22,
    ref: "react",
    img: "images/projectPics/KeeperApp.png",
    title: "Keeper App",
    code: "https://github.com/Ranjeet2311/Keeper-App",
    demo: "https://keeper-01.netlify.app/",
  },
  {
    id: 23,
    ref: "react",
    img: "images/projectPics/movie-database-project.png",
    title: "React-Movie Database",
    code: "https://github.com/Ranjeet2311/React-MovieDatabase-app",
    demo: "https://movie-database-project-0802.netlify.app/",
  },
  {
    id: 24,
    ref: "react",
    img: "images/projectPics/contact-manager.jpg",
    title: "Contact Manager",
    code: "https://github.com/Ranjeet2311/React-Contact-Mangaer",
    demo: "https://contact-manager-001.netlify.app/",
  },

  {
    id: 25,
    ref: "react",
    img: "images/projectPics/quiz-demo.jpg",
    title: "React-Quiz App",
    code: "https://github.com/Ranjeet2311/React-Quiz-App",
    demo: "https://quiz-app-0810.netlify.app/",
  },
  {
    id: 26,
    ref: "react",
    img: "images/projectPics/Text-to-speech-image.jpg",
    title: "React-Text to Speech",
    code: "https://github.com/Ranjeet2311/React-Speech-to-text",
    demo: "https://speech-to-text-09-01.netlify.app",
  },
  {
    id: 27,
    ref: "react",
    img: "images/projectPics/drone-comapny.jpg",
    title: "React-Drone Company",
    code: "https://github.com/Ranjeet2311/React--Sass-Website",
    demo: "https://drone-comapny.netlify.app/",
  },
  {
    id: 28,
    ref: "react",
    img: "images/projectPics/React-home.png",
    title: "React-React-Website",
    code: "https://github.com/Ranjeet2311/React-Website",
    demo: "https://react-website-0803.netlify.app/",
  },
  {
    id: 29,
    ref: "react",
    img: "images/projectPics/react-menu-home.png",
    title: "React-React Dynamic Menu",
    code: "https://github.com/Ranjeet2311/React-Navbar",
    demo: "https://react-navigation-menu-0803.netlify.app/",
  },
];

export default projectData;
