const projectData = [
  {
    id: 1,
    ref: 'vue',
    img: 'images/projectPics/music-app.png',
    title: 'Music Wallets (vue)',
    tags: [
      'javascript',
      'firebase',
      'firestore',
      'firebase-authentication',
      'Storage',
      'scss',
      'Html',
      'vue-components',
      'vue-router',
      'route-guards',
      'vue3',
      'bootstrap5',
      'composition-api',
      'crud-operation',
    ],
    code: 'https://github.com/Ranjeet2311/Music-Wallets',
    demo: 'https://music-at-tips.web.app/login',
  },
  {
    id: 2,
    ref: 'vue',
    img: 'images/projectPics/chat-app.png',
    title: 'Group Chat (vue)',
    tags: [
      'vue-components',
      'vue-router',
      'vue3',
      'firebase',
      'firestore',
      'firebase-authentication',
      'bootstrap5',
      'composition-api',
      'crud-operation',
      'vue-composable',
      'javascript',
      'Storage',
      'scss',
      'Html',
    ],
    code: 'https://github.com/Ranjeet2311/group-chat',
    demo: 'https://group-chat-2.netlify.app/',
  },
  {
    id: 3,
    ref: 'angular',
    img: 'images/projectPics/git-app.png',
    title: 'Github Repo browser (Angular)',
    tags: [
      'html',
      'graphql-api',
      'angular',
      'typescript',
      'rxjs',
      'interface',
      'mapping',
      'scss',
      'http-client',
      'observables',
      'lifecycle',
      'angular-router',
      'dynamic-routing ',
      'scss',
      'reactiveform-validation',
      'reactiveformsmodule',
      'list-filter',
    ],
    code: 'https://github.com/Ranjeet2311/GIthub-Repo-browser',
    demo: 'https://gith.netlify.app/',
  },
  {
    id: 4,
    ref: 'angular',
    img: 'images/projectPics/Appointment-App.png',
    title: 'Appointment tracker (Angular)',
    tags: [
      'html',
      'browser-memory',
      'angular',
      'typescript',
      'interface',
      'mapping',
      'scss',
      'http-client',
      'lifecycle',
      'angular-router',
      'scss',
      'list-filter',
    ],
    code: 'https://github.com/Ranjeet2311/Personal-appointment-booking',
    demo: 'https://tracker01.netlify.app/',
  },
  {
    id: 5,
    ref: 'react',
    img: 'images/projectPics/quiz-demo.jpg',
    title: 'Quiz App (React)',
    tags: [
      'eslint',
      'JavaScript XML',
      'Virtual DOM',
      'state management',
      'Props',
      'mapping',
      'javascript',
      'react',
      'Destructuring',
      'ES6',
      'scss',
      'useState',
      'lifecycle-hooks',
      'list-filter',
      'functional programming',
      'components',
      'useEffect',
      'mapping',
      'DOM',
    ],
    code: 'https://github.com/Ranjeet2311/React-Quiz-App',
    demo: 'https://quiz-app-0810.netlify.app/',
  },
  {
    id: 6,
    ref: 'react',
    img: 'images/projectPics/Text-to-speech-image.jpg',
    title: 'React-Text to Speech (React)',
    tags: [
      'state management',
      'eslint',
      'Props',
      'JavaScript XML',
      'Array',
      'Objects',
      'Virtual DOM',
      'react',
      'javascript',
      'scss',
      'lifecycle-hooks',
      'components',
      'useEffect',
      'scss',
      'list-filter',
      'functional programming',
      'mapping',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/React-Speech-to-text',
    demo: 'https://speech-to-text-09-01.netlify.app',
  },
  {
    id: 7,
    ref: 'vue',
    img: 'images/projectPics/counter-app.png',
    title: 'Simple Counter (vue)',
    tags: [
      'vue-components',
      'state management',
      'JavaScript',
      'methods',
      'data',
      'vue-router',
      'vue3',
      'javascript',
      'scss',
      'Html',
    ],
    code: 'https://github.com/Ranjeet2311/Vue-Counter',
    demo: 'https://dulcet-quokka-b7e591.netlify.app/',
  },
  {
    id: 8,
    ref: 'react',
    img: 'images/projectPics/KeeperApp.png',
    title: 'Keeper Ap (React)',
    tags: [
      'Material-Ui',
      'state management',
      'eslint',
      'Props',
      'filter',
      'JavaScript XML',
      'Virtual DOM',
      'Array',
      'Objects',
      'react',
      'javascript',
      'scss',
      'lifecycle-hooks',
      'components',
      'useEffect',
      'scss',
      'list-filter',
      'functional programming',
      'mapping',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/Keeper-App',
    demo: 'https://keeper-01.netlify.app/',
  },
  {
    id: 9,
    ref: 'react',
    img: 'images/projectPics/movie-database-project.png',
    title: 'Movie Database (React)',
    tags: [
      'axios',
      'eslint',
      'state management',
      'lifecycle-hooks',
      'Props',
      'filter',
      'Array',
      'Objects',
      'JavaScript XML',
      'Virtual DOM',
      'react',
      'javascript',
      'scss',
      'components',
      'useEffect',
      'scss',
      'list-filter',
      'functional programming',
      'mapping',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/React-MovieDatabase-app',
    demo: 'https://movie-database-project-0802.netlify.app/',
  },
  {
    id: 10,
    ref: 'react',
    img: 'images/projectPics/contact-manager.jpg',
    title: 'Contact Manager (React)',
    tags: [
      'Material-Ui',
      'eslint',
      'JavaScript XML',
      'Array',
      'filter',
      'Objects',
      'Props',
      'state management',
      'lifecycle-hooks',
      'Virtual DOM',
      'react',
      'javascript',
      'scss',
      'components',
      'useEffect',
      'scss',
      'list-filter',
      'functional programming',
      'mapping',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/React-Contact-Mangaer',
    demo: 'https://contact-manager-001.netlify.app/',
  },

  {
    id: 11,
    ref: 'react',
    img: 'images/projectPics/drone-comapny.jpg',
    title: 'Drone Company (React)',
    tags: [
      'react-dom',
      'react-router-dom',
      'eslint',
      'JavaScript XML',
      'Props',
      'animations',
      'state management',
      'lifecycle-hooks',
      'filter',
      'Virtual DOM',
      'react',
      'javascript',
      'scss',
      'child components',
      'useEffect',
      'functional programming',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/React--Sass-Website',
    demo: 'https://drone-comapny.netlify.app/',
  },
  {
    id: 12,
    ref: 'react',
    img: 'images/projectPics/React-home.png',
    title: 'React-Website (React)',
    tags: [
      'Material-Ui',
      'eslint',
      'react-dom',
      'react-router-dom',
      'JavaScript XML',
      'Array',
      'filter',
      'Objects',
      'Props',
      'state management',
      'lifecycle-hooks',
      'Virtual DOM',
      'react',
      'javascript',
      'scss',
      'components',
      'useEffect',
      'scss',
      'list-filter',
      'functional programming',
      'mapping',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/React-Website',
    demo: 'https://react-website-0803.netlify.app/',
  },
  {
    id: 13,
    ref: 'react',
    img: 'images/projectPics/react-menu-home.png',
    title: 'React Dynamic Menu (React)',
    tags: [
      'react-dom',
      'react-router-dom',
      'eslint',
      'JavaScript XML',
      'Props',
      'animations',
      'state management',
      'lifecycle-hooks',
      'filter',
      'Virtual DOM',
      'react',
      'javascript',
      'scss',
      'child components',
      'useEffect',
      'functional programming',
      'DOM',
      'Destructuring',
      'ES6',
    ],
    code: 'https://github.com/Ranjeet2311/React-Navbar',
    demo: 'https://react-navigation-menu-0803.netlify.app/',
  },

  {
    id: 14,
    ref: 'funApp',
    img: 'images/projectPics/to-do-tasks.jpg',
    title: ' To-do-app',
    code: 'https://github.com/Ranjeet2311/To-Do-App-Vanilla-JS',
    demo: 'https://old-portfolio0.netlify.app/app-demo/todo.html',
  },
  {
    id: 15,
    ref: 'funApp',
    img: 'images/projectPics/Weather.jpg',
    title: 'Weathe App',
    code: 'https://github.com/Ranjeet2311/Weather-App',
    demo: 'https://old-portfolio0.netlify.app/app-demo/weather.html',
  },

  {
    id: 16,
    ref: 'funApp',
    img: 'images/projectPics/qr-code-bg.jpg',
    title: ' QR-Code Generator',
    code: 'https://github.com/Ranjeet2311/Qr-Code-Generator',
    demo: 'https://qr-code-25-11.netlify.app/',
  },
  {
    id: 17,
    ref: 'funApp',
    img: 'images/projectPics/Personality-match.jpg',
    title: 'Personality Match',
    code: 'https://github.com/Ranjeet2311/Personality-Match',
    demo: 'https://personality-match.netlify.app/',
  },

  {
    id: 18,
    ref: 'funApp',
    img: 'images/projectPics/weight-converter.jpg',
    title: ' Weight converter',
    code: 'https://github.com/Ranjeet2311/Weight-Converter',
    demo: 'https://old-portfolio0.netlify.app/app-demo/weight-converter.html',
  },

  {
    id: 19,
    ref: 'funApp',
    img: 'images/projectPics/music-player.jpg',
    title: 'Music player',
    code: 'https://github.com/Ranjeet2311/Music-player',
    demo: 'https://old-portfolio0.netlify.app/app-demo/music-player.html',
  },

  {
    id: 20,
    ref: 'funApp',
    img: 'images/projectPics/counter.jpg',
    title: 'Counter',
    code: 'https://github.com/Ranjeet2311/Counter-',
    demo: 'https://old-portfolio0.netlify.app/app-demo/counter.html',
  },

  {
    id: 21,
    ref: 'funApp',
    img: 'images/projectPics/Digital-Clock.jpg',
    title: ' Digital clock',
    code: 'https://github.com/Ranjeet2311/Digital-Clock',
    demo: 'https://old-portfolio0.netlify.app/app-demo/digital-clock.html',
  },

  {
    id: 22,
    ref: 'funApp',
    img: 'images/projectPics/play-music.jpg',
    title: 'Tap the music',
    code: 'https://github.com/Ranjeet2311/Tap-the-Music',
    demo: 'https://old-portfolio0.netlify.app/app-demo/play-music.html',
  },

  {
    id: 23,
    ref: 'funApp',
    img: 'images/projectPics/Menu-display.jpg',
    title: 'Menu display -filter',
    code: 'https://github.com/Ranjeet2311/Dynamic-Menu-Display',
    demo: 'https://old-portfolio0.netlify.app/app-demo/menu-display.html',
  },

  {
    id: 24,
    ref: 'funApp',
    img: 'images/projectPics/modal.jpg',
    title: 'Best pictures from Europe',
    code: 'https://github.com/Ranjeet2311/Modal',
    demo: 'https://old-portfolio0.netlify.app/app-demo/modal.html',
  },
  {
    id: 25,
    ref: 'funApp',
    img: 'images/projectPics/diceGame.png',
    title: 'Dice Game',
    code: 'https://github.com/Ranjeet2311/Dice-Game',
    demo: 'https://dazzling-heisenberg-3851ef.netlify.app/',
  },
  {
    id: 26,
    ref: 'template',
    img: 'images/projectPics/Av-st-Template-demo.PNG',
    title: 'Av-st-Template',
    code: 'https://github.com/Ranjeet2311/frontend-_AV',
    demo: 'https://av-st-template.netlify.app/',
  },
  {
    id: 27,
    ref: 'template',
    img: 'images/projectPics/form-validation-e.jpg',
    title: 'Form validation',
    code: 'https://github.com/Ranjeet2311/Parcel-bundler',
    demo: 'https://render-007.netlify.app/',
  },
  {
    id: 28,
    ref: 'template',
    img: 'images/projectPics/yoga-demo.png',
    title: 'Yoga-demo',
    code: 'https://github.com/Ranjeet2311/Projects',
    demo: 'https://old-portfolio0.netlify.app/app-demo/yoga-demo.html',
  },
  {
    id: 29,
    ref: 'template',
    img: 'images/projectPics/tech-demo.jpg',
    title: 'Tech-demo',
    code: 'https://github.com/Ranjeet2311/Projects',
    demo: 'https://old-portfolio0.netlify.app/app-demo/tech-demo.html',
  },
  {
    id: 30,
    ref: 'template',
    img: 'images/projectPics/car-service-demo.png',
    title: 'Car service demo',
    code: 'https://github.com/Ranjeet2311/Projects',
    demo: 'https://old-portfolio0.netlify.app/app-demo/car-service.html',
  },
  {
    id: 31,
    ref: 'template',
    img: 'images/projectPics/game-sign-up.png',
    title: 'Game-sign-up',
    code: 'https://github.com/Ranjeet2311/Projects',
    demo: 'https://old-portfolio0.netlify.app/app-demo/hero-page.html',
  },
  {
    id: 32,
    ref: 'template',
    img: 'images/projectPics/my-portfolio.png',
    title: 'Old portfolio',
    code: 'https://github.com/Ranjeet2311/Ranjeet2311.github.io',
    demo: 'https://old-portfolio0.netlify.app/',
  },
  {
    id: 33,
    ref: 'template',
    img: 'images/projectPics/Animated-Boat.jpg',
    title: 'Animated Boat',
    code: 'https://github.com/Ranjeet2311/Boat-Animation',
    demo: 'https://old-portfolio0.netlify.app/app-demo/animatedBoat.html',
  },
  {
    id: 34,
    ref: 'template',
    img: 'images/projectPics/e-commerce-demo.png',
    title: 'E-commerce-demo',
    code: 'https://github.com/Ranjeet2311/Projects',
    demo: 'https://old-portfolio0.netlify.app/app-demo/e-commerce-demo.html',
  },

  // {
  //   id: 34,
  //   ref: 'angular',
  //   img: 'images/projectPics/angular-todo.png',
  //   title: 'Todo-Angular',
  //   code: 'https://github.com/Ranjeet2311/Todo-Angular',
  //   demo: 'https://adorable-phoenix-646f30.netlify.app/',
  // },
];

export default projectData;
